program loss_rate
    !! @todo there are a lot of redundancies between Solver_t and Potential_t
    !! clean it up! @endtodo
    !! as of right now, my program is basically a refactoring of Thijssen's
    !! chapter two exercise solution
    !! however, it looks like his approach is different from what is outlined
    !! in his book. The book makes more sense to me, so I will refactor further
    !! to match that
    !! test against /home/jph/thijssen/ch2/sigmadat
    ! (generated by solution to textbook exercise, provided by the author)
    ! use, intrinsic :: iso_fortran_env, only: rp => real32
    ! use json_module
    ! use precision, only: rp
    ! use mpi_f08
    ! use potential_type, only: Potential_Harmonic_t
    !! @todo problem seems to come from numerov on LJ potential
    use solver_type, only: Solver_t
    implicit none
    type(Solver_t) :: model

    model = Solver_t()
    print*, model%pot%alpha
    print*, model%rstep
    !! @todo it looks like alpha get initialised to zero for some reason!?
    call model%calc_full_cross_section()

    contains


end program loss_rate
